### ISSUE TITLE
Logo offer for Tasty baking

### ISSUE THREAD

**Issue by familqasimov** [neone35/tasty-baking#1]
Hi sir Artur. I'm graphic designer. I would like to offer logo for your current project. If you like I can give you all the formats of the design free. If you want a change please specify.

# Logo
![untitled-1](https://user-images.githubusercontent.com/36432269/42176798-439102da-7e3b-11e8-8594-377309ec465d.png)

**Comment by familqasimov** [comment]
![2](https://user-images.githubusercontent.com/36432269/42182081-3baa47a8-7e4e-11e8-9cbd-c923331964e1.png)

**Comment by neone35** [comment]
No, thanks. This is not a production project. I'm okay with current one.
